### ISSUE TITLE
Formulário Criação e Edição de Produtos

### ISSUE THREAD

**Issue by gabrielbdornas** [liberom/festoo#70]
acho que deveríamos trocar o botão incluir para editar na view de edição do produto

**Comment by liberom** [comment]
Vamos trocar pra Salvar então pq é o mesmo formulário para os dois casos

**Comment by gabrielbdornas** [comment]
criei um branch já com a mudança do botão para salvar (new-edit-product) não fiz o pull request pq estou aguardando o merge do branch amont.

**Comment by liberom** [comment]
ok
