### ISSUE TITLE
Product show

### ISSUE THREAD

**Issue by gabrielbdornas** [liberom/festoo#71]
Na view show product podemos colocar no título o nome do produto e não a categoria à qual ele se enquadra?

Além disso, acredito que esta view deveria cair na página de edição do produto caso o dono do produto seja o usuário logado. Caso contrário ela cairia na página de locação (quadro de agendamento do lado direito da tela)

**Comment by liberom** [comment]
Conversa com a Débora, pq a página show é o bebê dela

**Comment by liberom** [comment]
@deboragoistorres

**Comment by gabrielbdornas** [comment]
Débora resolveu este problema
